{{- if .Values.exporter.target }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: exporter
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "gentrail.labels" (merge (dict "component" "exporter") .) | indent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.exporter | quote }}
{{- end }}
